# Generated by Django 3.0.8 on 2020-07-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='phone_no',
            field=models.CharField(max_length=11),
        ),
    ]
